apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 1 # tells deploym ent to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: 101.132.172.54:5000/ricky:latest
        command: [ "/bin/sh", "-c", "/usr/init.sh"]
        ports:
        - containerPort: 80 #容器开放的端口，即使是80也要显示指定
        - containerPort: 443 # 也开放了https端口
      nodeName: yang

---

apiVersion: v1
kind: Service
metadata:
  name: demo-svc
spec:
  ports:
  - port: 80
    targetPort: 80 # Docker实例的端口
    nodePort: 31112  # 暴露给外网的端口
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443 # Docker实例的端口
    nodePort: 31113  # 暴露给外网的端口
    protocol: TCP
    name: https
  type: NodePort
  selector:
    app: demo