apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 1 # tells deploym ent to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: 101.132.172.54:5000/ricky:latest
        command: [ "/bin/sh", "-c", "/usr/init.sh"]
        ports:
        - containerPort: 5631

---

apiVersion: v1
kind: Service
metadata:
  name: demo-deployment
  labels:
    run: demo-deployment
spec:
  ports:
  - port: 80
    targetPort: 5631 # Docker实例的端口
    nodePort: 31112  # 暴露给外网的端口
    protocol: TCP
  selector:
    run: demo-deployment