apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  rules:
  - host: learn.ricky.pro
    http:
      paths:
      - path: /demo
        backend:
          serviceName: demo-svc
          servicePort: 5631
