apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-mydemo
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: sh2.ricky.pro
    http:
      paths:
      - path: /ab
        backend:
          serviceName: mydemo01svc
          servicePort: 80
  - host: sh2.ricky.pro
    http:
      paths:
      - path: /cd
        backend:
          serviceName: mydemo02svc
          servicePort: 8080