apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-mydemo
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: ingress1.ricky.pro
    http:
      paths:
      - path:
        backend:
          serviceName: mydemo01svc
          servicePort: 80
  - host: ingress2.ricky.pro
    http:
      paths:
      - path:
        backend:
          serviceName: mydemo02svc
          servicePort: 8080