apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 1 # tells deploym ent to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: 101.132.172.54:5000/ricky:0.0.1
        imagePullPolicy: Always
        command: [ "/bin/sh", "-c", "/usr/init.sh"]
        ports:
        - containerPort: 80 #容器开放的端口，即使是80也要显示指定
        - containerPort: 443 # 也开放了https端口
        volumeMounts: # 加载在宿主机上定义的卷
        - mountPath: "/usr/share/nginx/html/host.html" # Container内部的文件路径
          name: sample-volume # 宿主机上卷的名字
          readOnly: true
      nodeName: yang # 将pod运行在指定的机器上
      volumes:
      - name: sample-volume #在宿主机上定义的配置文件
        hostPath:
          type: File
          path: /etc/host.html

---

apiVersion: v1
kind: Service
metadata:
  name: demo-svc
spec:
  ports:
  - port: 80
    targetPort: 80 # Docker实例的端口
    nodePort: 31112  # 暴露给外网的端口
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443 # Docker实例的端口
    nodePort: 31113  # 暴露给外网的端口
    protocol: TCP
    name: https
  type: NodePort # k8s会向外网暴露端口，如果是在阿里云上，阿里云需要将相应的端口设置成白名单
  selector:
    app: demo